var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "title": "Click to enter Plot title", 
        "yaxis": {
            "range": [
                -40.44444444444444, 
                768.4444444444445
            ], 
            "title": "Bookings", 
            "type": "linear", 
            "autorange": true, 
            "showgrid": true
        }, 
        "showlegend": true, 
        "breakpoints": [], 
        "xaxis": {
            "showticklabels": true, 
            "title": "Days", 
            "showgrid": false, 
            "range": [
                0, 
                61
            ], 
            "zeroline": false, 
            "showline": false, 
            "nticks": 13, 
            "type": "category", 
            "autorange": true, 
            "exponentformat": "none", 
            "side": "bottom"
        }, 
        "hovermode": "x", 
        "legend": {
            "y": 1, 
            "x": 1.02, 
            "traceorder": "reversed", 
            "borderwidth": 0, 
            "orientation": "v"
        }
    }, 
    "data": [
        {
            "showlegend": true, 
            "autobinx": true, 
            "name": "Parked", 
            "ysrc": "tahtah:1:ee1aac", 
            "hoverinfo": "y+text", 
            "xsrc": "tahtah:1:7af259", 
            "mode": "lines", 
            "visible": true, 
            "textsrc": "tahtah:1:7af259", 
            "text": [
                "29th Aug", 
                "30th Aug", 
                "31st Aug", 
                "1st Sep", 
                "2nd Sep", 
                "3rd Sep", 
                "4th Sep", 
                "5th Sep", 
                "6th Sep", 
                "7th Sep", 
                "8th Sep", 
                "9th Sep", 
                "10th Sep", 
                "11th Sep", 
                "12th Sep", 
                "13th Sep", 
                "14th Sep", 
                "15th Sep", 
                "16th Sep", 
                "17th Sep", 
                "18th Sep", 
                "19th Sep", 
                "20th Sep", 
                "21st Sep", 
                "22nd Sep", 
                "23rd Sep", 
                "24th Sep", 
                "25th Sep", 
                "26th Sep", 
                "27th Sep", 
                "28th Sep", 
                "29th Sep", 
                "30th Sep", 
                "1st Oct", 
                "2nd Oct", 
                "3rd Oct", 
                "4th Oct", 
                "5th Oct", 
                "6th Oct", 
                "7th Oct", 
                "8th Oct", 
                "9th Oct", 
                "10th Oct", 
                "11th Oct", 
                "12th Oct", 
                "13th Oct", 
                "14th Oct", 
                "15th Oct", 
                "16th Oct", 
                "17th Oct", 
                "18th Oct", 
                "19th Oct", 
                "20th Oct", 
                "21st Oct", 
                "22nd Oct", 
                "23rd Oct", 
                "24th Oct", 
                "25th Oct", 
                "26th Oct", 
                "27th Oct", 
                "28th Oct", 
                "29th Oct"
            ], 
            "y": [
                "355", 
                "369", 
                "427", 
                "633", 
                "435", 
                "412", 
                "401", 
                "420", 
                "394", 
                "483", 
                "550", 
                "341", 
                "343", 
                "298", 
                "339", 
                "338", 
                "399", 
                "459", 
                "289", 
                "274", 
                "266", 
                "218", 
                "248", 
                "311", 
                "310", 
                "210", 
                "191", 
                "163", 
                "185", 
                "183", 
                "209", 
                "201", 
                "140", 
                "125", 
                "110", 
                "123", 
                "133", 
                "162", 
                "166", 
                "102", 
                "86", 
                "87", 
                "104", 
                "99", 
                "131", 
                "131", 
                "89", 
                "71", 
                "92", 
                "97", 
                "110", 
                "162", 
                "202", 
                "139", 
                "95", 
                "84", 
                "69", 
                "99", 
                "109", 
                "134", 
                "74", 
                "1"
            ], 
            "x": [
                "29th Aug", 
                "30th Aug", 
                "31st Aug", 
                "1st Sep", 
                "2nd Sep", 
                "3rd Sep", 
                "4th Sep", 
                "5th Sep", 
                "6th Sep", 
                "7th Sep", 
                "8th Sep", 
                "9th Sep", 
                "10th Sep", 
                "11th Sep", 
                "12th Sep", 
                "13th Sep", 
                "14th Sep", 
                "15th Sep", 
                "16th Sep", 
                "17th Sep", 
                "18th Sep", 
                "19th Sep", 
                "20th Sep", 
                "21st Sep", 
                "22nd Sep", 
                "23rd Sep", 
                "24th Sep", 
                "25th Sep", 
                "26th Sep", 
                "27th Sep", 
                "28th Sep", 
                "29th Sep", 
                "30th Sep", 
                "1st Oct", 
                "2nd Oct", 
                "3rd Oct", 
                "4th Oct", 
                "5th Oct", 
                "6th Oct", 
                "7th Oct", 
                "8th Oct", 
                "9th Oct", 
                "10th Oct", 
                "11th Oct", 
                "12th Oct", 
                "13th Oct", 
                "14th Oct", 
                "15th Oct", 
                "16th Oct", 
                "17th Oct", 
                "18th Oct", 
                "19th Oct", 
                "20th Oct", 
                "21st Oct", 
                "22nd Oct", 
                "23rd Oct", 
                "24th Oct", 
                "25th Oct", 
                "26th Oct", 
                "27th Oct", 
                "28th Oct", 
                "29th Oct"
            ], 
            "autobiny": true, 
            "type": "scatter", 
            "fill": "tonexty"
        }, 
        {
            "showlegend": true, 
            "autobinx": true, 
            "name": "In", 
            "ysrc": "tahtah:0:47eb25", 
            "hoverinfo": "y+text", 
            "xsrc": "tahtah:0:acd6de", 
            "mode": "lines", 
            "textsrc": "tahtah:0:acd6de", 
            "text": [
                "29th Aug", 
                "30th Aug", 
                "31st Aug", 
                "1st Sep", 
                "2nd Sep", 
                "3rd Sep", 
                "4th Sep", 
                "5th Sep", 
                "6th Sep", 
                "7th Sep", 
                "8th Sep", 
                "9th Sep", 
                "10th Sep", 
                "11th Sep", 
                "12th Sep", 
                "13th Sep", 
                "14th Sep", 
                "15th Sep", 
                "16th Sep", 
                "17th Sep", 
                "18th Sep", 
                "19th Sep", 
                "20th Sep", 
                "21st Sep", 
                "22nd Sep", 
                "23rd Sep", 
                "24th Sep", 
                "25th Sep", 
                "26th Sep", 
                "27th Sep", 
                "28th Sep", 
                "29th Sep", 
                "30th Sep", 
                "1st Oct", 
                "2nd Oct", 
                "3rd Oct", 
                "4th Oct", 
                "5th Oct", 
                "6th Oct", 
                "7th Oct", 
                "8th Oct", 
                "9th Oct", 
                "10th Oct", 
                "11th Oct", 
                "12th Oct", 
                "13th Oct", 
                "14th Oct", 
                "15th Oct", 
                "16th Oct", 
                "17th Oct", 
                "18th Oct", 
                "19th Oct", 
                "20th Oct", 
                "21st Oct", 
                "22nd Oct", 
                "23rd Oct", 
                "24th Oct", 
                "25th Oct", 
                "26th Oct", 
                "27th Oct", 
                "28th Oct", 
                "29th Oct"
            ], 
            "y": [
                "607", 
                "617", 
                "635", 
                "702", 
                "728", 
                "541", 
                "529", 
                "358", 
                "349", 
                "376", 
                "481", 
                "463", 
                "368", 
                "395", 
                "337", 
                "366", 
                "361", 
                "508", 
                "463", 
                "360", 
                "389", 
                "287", 
                "304", 
                "325", 
                "479", 
                "391", 
                "315", 
                "308", 
                "228", 
                "237", 
                "285", 
                "366", 
                "357", 
                "215", 
                "228", 
                "153", 
                "177", 
                "154", 
                "249", 
                "220", 
                "171", 
                "145", 
                "126", 
                "120", 
                "148", 
                "159", 
                "158", 
                "97", 
                "131", 
                "103", 
                "95", 
                "93", 
                "136", 
                "135", 
                "95", 
                "88", 
                "88", 
                "105", 
                "127", 
                "173", 
                "195", 
                "0"
            ], 
            "x": [
                "29th Aug", 
                "30th Aug", 
                "31st Aug", 
                "1st Sep", 
                "2nd Sep", 
                "3rd Sep", 
                "4th Sep", 
                "5th Sep", 
                "6th Sep", 
                "7th Sep", 
                "8th Sep", 
                "9th Sep", 
                "10th Sep", 
                "11th Sep", 
                "12th Sep", 
                "13th Sep", 
                "14th Sep", 
                "15th Sep", 
                "16th Sep", 
                "17th Sep", 
                "18th Sep", 
                "19th Sep", 
                "20th Sep", 
                "21st Sep", 
                "22nd Sep", 
                "23rd Sep", 
                "24th Sep", 
                "25th Sep", 
                "26th Sep", 
                "27th Sep", 
                "28th Sep", 
                "29th Sep", 
                "30th Sep", 
                "1st Oct", 
                "2nd Oct", 
                "3rd Oct", 
                "4th Oct", 
                "5th Oct", 
                "6th Oct", 
                "7th Oct", 
                "8th Oct", 
                "9th Oct", 
                "10th Oct", 
                "11th Oct", 
                "12th Oct", 
                "13th Oct", 
                "14th Oct", 
                "15th Oct", 
                "16th Oct", 
                "17th Oct", 
                "18th Oct", 
                "19th Oct", 
                "20th Oct", 
                "21st Oct", 
                "22nd Oct", 
                "23rd Oct", 
                "24th Oct", 
                "25th Oct", 
                "26th Oct", 
                "27th Oct", 
                "28th Oct", 
                "29th Oct"
            ], 
            "autobiny": true, 
            "type": "scatter", 
            "fill": "tonexty"
        }
    ]
}